

from components.device_tracker import publish_discovery_message_for_device_tracker
from components.scan_all_button import publish_discovery_message_for_scan_all_button
from components.scan_device_button import publish_discovery_message_for_scan_button
from components.scan_timeout_number import publish_discovery_message_for_timeout

def run_discovery(devices: list[str]):
	publish_discovery_message_for_timeout()
	publish_discovery_message_for_scan_all_button()

	for device in devices:
		publish_discovery_message_for_device_tracker(device)
		publish_discovery_message_for_scan_button(device)